name: 080-resusable-workflow-caller

on:
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: karunakar1008/github-actions-learnings/blob/main/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: Karunakar
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: karunakar1008/github-actions-learnings/blob/main/.github/workflows/080-reusable-workflow-called.yml@main
    with:
      username: Bhogyari
    secrets:
      token: ${{ secrets.TOKEN }}